services:
  skillsbuildapplicationswcopilotagentmode:
    image: skillsbuildapplicationswcopilotagentmode
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
